config/routes.rb
Rails.application.routes.draw do
  devise_for :host_users
  root to: 'lodgings#index'
  
  resources :lodgings do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host_user.rb
class HostUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lodgings

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/ } do
    validates :hostname
  end
  
  with_options presence: true, format: { with: /\A[ア-ヶ一ー]+\z/ } do
    validates :hostname_kana
  end
  
  with_options presence: true do
    validates :nickname
    validates :phone, format: { with: /[0-9]{6,11}/ }, length: { maximum: 11 }
    validates :age
    validates :gender
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, presence: true, format: PASSWORD_REGEX, length: { minimum: 6 }
end

app/models/lodging.rb
class Lodging < ApplicationRecord
  # extend ActiveHash::Associations::ActiveRecordExtensions


  belongs_to :host_user
  has_many_attached :images, dependent: :destoy

  validates :price, presence: true, numericality: { with: /[0-9]/ }

  with_options presence: true do
    validates :lodge_name
    validates :price, inclusion: { in: 999..9_999_999 }
    validates :postcode, format: { with: /\A[0-9]{3}-[0-9]{4}\z/ }
    validates :prefecture_city
    validates :block_number
    validates :phone, format: { with: /\A^0\d{1,3}-\d{1,4}-\d{4}$\z/ }
    validates :description
    validates :images
  end

  def self.search(search)
    if search != ""
      Lodging.where('prefecture_city LIKE(?)', "%#{search}%")
    else
      Lodging.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :hostname, :hostname_kana, :phone, :age, :gender])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :hostname, :hostname_kana, :phone, :age, :gender])
  end
end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :set_lodge, only: [:show, :edit, :destroy]

  def index
    @lodges = Lodging.all.order('created_at DESC')
  end

  def new
    @lodge = Lodging.new
  end

  def create
    @lodge = Lodging.new(lodge_params)
    if @lodge.valid?
      @lodge.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    lodge = Lodging.find(params[:id])
    if lodge.valid?
      lodge.update(lodge_params)
      redirect_to lodging_path(lodge.id)
    else
      render :edit
    end
  end

  def destroy
    if @lodge.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @lodges = Lodging.search(params[:keyword])
  end

  private

  def lodge_params
    params.require(:lodging).permit(:lodge_name, :price, :postcode, :prefecture_city, :block_number, :building, :phone, :description, images: []).merge(host_user_id: current_host_user.id)

  end

  def set_lodge
    @lodge = Lodging.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Riderhouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <script src="https://kit.fontawesome.com/ae62ef2abc.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lodgings/edit.html.erb
<%# CSSは、宿登録ページの物を使用 %>
<%= render "shared/header" %>

<div class="lodge-addmain">
  <%= form_with model: @lodge, local: true do |f| %>
    <div class="lodge-address">
      <div class="lodge-description">
        <div class="message1">宿を登録</div>
        <div class="message2">予約されるまでは、詳細な情報は公開されません。</div>
      </div>

      <div class="name-price">
        <div class="form-group">
          <label for="namelabel">
          宿の名前は？
          <span class="indispensable">必須</span>
          </label>
        </div>
        <%= f.text_field :lodge_name, class:'lodge-text', id:'namelabel', placeholder:'例) ライダーハウス'%>

        <div class="form-group price-box">
          <label for="pricelabel">
          1泊の値段は？
          <span class="indispensable">必須</span>
          </label>
        </div>
        <%= f.text_field :price, class:'lodge-text', id:'pricelabel', placeholder:'例) 3000'%>
      </div>

      <div class="form-group">
        <label for="postlabel">
        郵便番号
        <span class="indispensable">必須</span>
        </label>
      </div>
      <%= f.text_field :postcode, class:'lodge-text', id:'postlabel', placeholder:'例) 102-3456' %>

      <div class="form-group">
        <label for="pref-city">
        都道府県&市区町村
        <span class="indispensable">必須</span>
        </label>
      </div>
      <%= f.text_field :prefecture_city, class:'lodge-text', id:'pref-city', placeholder: '例)東京都新宿区' %>

      <div class="form-group">
        <label for="blocklabel">
        番地
        <span class="indispensable">必須</span>
        </label>
      </div>
      <%= f.text_field :block_number, class:'lodge-text', id:'blocklabel', placeholder:'例) 新宿1-1-1' %>
          
      <div class="form-group">
        <label for="buildinglabel">
        建物名
        </label>
      </div>
      <%= f.text_field :building, class:'lodge-text', id:'buildinglabel', placeholder:'例) 新宿ビル'%>

      <div class="form-group">
        <label for="lodge-desc">
        この宿について
        <span class="indispensable">必須</span>
        </label>
      </div>
      <%= f.text_area :description, class:"lodge-text", id:"lodge-desc", placeholder:"宿の説明", rows:"7" ,maxlength:"1000" %>


      <%= f.file_field :images, name: 'lodging[images][]', id: 'lodging_image' %>
      <div id="edit-image">
        <% @lodge.images.each do |image| %>
          <%= image_tag image, class: 'images' %>
        <% end %>  
      </div>


      <div class="btn">
        <%= f.submit '内容を更新する', class:'provide-btn' %>
      </div>
      <%= link_to '戻る', lodging_path(@lodge.id), class:'back-btn' %>
    </div>
  <% end %>
</div>

app/views/lodgings/index.html.erb
<%= render "shared/header" %>

<body>
  <div class="container-fluid">
    <div class="row">
      <%= image_tag "homeindex_moter.jpg", class: 'title-img'%>
    </div>
  </div>

  <h3 class="text-center bg-light font-weight-bold mt-5 my-3">全国の宿一覧</h3>

  <div class="containr">
    <% @lodges.each do |lodge| %>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">

        <div class="col card mt-5 mx-auto d-flexbox" style="width: 11rem;">
          <div class="card-img-top swiper-container swoper-container-initialized swiper-container-vertical">
            <div class="swiper-wrapper">
              <% lodge.images.each do |image| %>
                <div class="swiper-slide">
                  <%= link_to lodging_path(lodge.id), method: :get do %>
                    <%= image_tag image, class:'images'%>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
          </div>

          <div class="card-body text-center">
            <h4 class="card-title center">
              <%= lodge.lodge_name %>
            </h4>
            <h6 class="card-subtitle">
              <%= lodge.prefecture_city %>
            </h6>
            <p class="card-subtitle mt-2" style="color: red;">
              ￥<%= lodge.price %>/泊
            </p>
          </div>
        </div>

      </div>
    <% end %>
  </div>

  <footer>©️ Kanako Kurasawa2020</footer>

  <script>
    var Swiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    loop: true,
    
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },

    scrollbar: {
      el: '.swiper-scrollbar',
    },
  });
  </script>
</body>

app/views/lodgings/new.html.erb
<body>
  <header class="new_header">
    <%= render "shared/header" %>
  </header>

  <main>
    <div class="lodge-addmain">

      <%= form_with model: @lodge, local: true do |f| %>

        <%= render "shared/error_msg", model: f.object %>
        
        <div class="lodge-address">
          <div class="lodge-description">
            <div class="message1">宿を登録</div>
            <div class="message2">
              公開される地図情報はおおよそのエリアです。
            </div>
          </div>

          <div class="name-price">
            <div class="form-group">
              <label for="namelabel">
              宿の名前は？
              <span class="indispensable">必須</span>
              </label>
            </div>
            <%= f.text_field :lodge_name, class:'lodge-text', id:'namelabel', placeholder:'例) ライダーハウス'%>

            <div class="form-group price-box">
              <label for="pricelabel">
              1泊の値段は？
              <span class="indispensable">必須</span>
              </label>
            </div>
            <%= f.text_field :price, class:'lodge-text', id:'pricelabel', placeholder:'例) 3000'%>
          </div>

          <div class="form-group">
            <label for="postlabel">
            郵便番号
            <span class="indispensable">必須</span>
            </label>
          </div>
          <%= f.text_field :postcode, class:'lodge-text', id:'postlabel', placeholder:'例) 102-3456' %>

          <div class="form-group">
            <label for="pref-city">
              都道府県&市区町村
            <span class="indispensable">必須</span>
            </label>
          </div>
          <%= f.text_field :prefecture_city, class:'lodge-text', id:'pref-city', placeholder: '例)東京都新宿区' %>

          <div class="form-group">
            <label for="blocklabel">
            番地
            <span class="indispensable">必須</span>
            </label>
          </div>
          <%= f.text_field :block_number, class:'lodge-text', id:'blocklabel', placeholder:'例) 新宿1-1-1' %>
        
          <div class="form-group">
            <label for="buildinglabel">
            建物名
            </label>
          </div>
          <%= f.text_field :building, class:'lodge-text', id:'buildinglabel', placeholder:'例) 新宿ビル'%>

          <div class="form-group">
            <label for="phonelabel">
            電話番号
            <span class="indispensable">必須</span>
            </label>
          </div>
          <%= f.text_field :phone, class:'lodge-text', id:'phonelabel', placeholder:'例) 01-1021-3456' %>

          <div class="form-group">
            <label for="lodge-desc">
            この宿について
            <span class="indispensable">必須</span>
            </label>
          </div>
          <%= f.text_area :description, class:"lodge-text", id:"lodge-desc", placeholder:"宿の説明", rows:"7" ,maxlength:"1000" %>


          <%= f.file_field :images, name: 'lodging[images][]', id: 'lodging_image' %>
          <div id="image-list"></div>


          <div class="btn">
            <%= f.submit '宿を登録する', class:'provide-btn' %>
          </div>
          <%= link_to '戻る', root_path, class:'back-btn' %>
        </div>
      <% end %>

      <% @lodge.images.each do |image| %>
        <%= image_tag image, class: 'images' %>
      <% end %>
        
    </div>
  </main>
</body>

app/views/lodgings/search.html.erb
<%= render "shared/header" %>


  <h3 class="center mt-5">
    <i class="fas fa-search"></i>検索結果
  </h3>
  <% @lodges.each do |lodge| %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">

      <div class="col card mt-5 mx-auto d-flexbox" style="width: 11rem;">
        <div class="card-img-top swiper-container swoper-container-initialized swiper-container-vertical">
          <div class="swiper-wrapper">
            <% lodge.images.each do |image| %>
              <div class="swiper-slide">
                <%= link_to lodging_path(lodge.id), method: :get do %>
                  <%= image_tag image, class:'images'%>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>

        <div class="card-body text-center">
          <h4 class="card-title center">
            <%= lodge.lodge_name %>
          </h4>
          <h6 class="card-subtitle">
            <%= lodge.prefecture_city %>
          </h6>
          <p class="card-subtitle mt-2" style="color: red;">
            ￥<%= lodge.price %>/泊
          </p>
        </div>
      </div>

    </div>
  <%end%>

  <footer>©️ Kanako Kurasawa2020</footer>

  <script>
    var Swiper = new Swiper('.swiper-container', {
    direction: 'vertical',
    loop: true,
    
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },

    scrollbar: {
      el: '.swiper-scrollbar',
    },
  });
  </script>
</div>

app/views/lodgings/show.html.erb
<body>
  <header>
    <%= render "shared/header" %>
  </header>

  <main id="site-content">
    <div class="top">
      <div class="top-text" style="max-width: 1120px;">
        <p class="title lodge_name" style="font-size: 35px;">
          <%= @lodge.lodge_name %>
        </p>
      </div>
      <div class="top-area">
        <section class="where-lodge mb-5">
          <i class="fas fa-map-marker-alt"><%= @lodge.prefecture_city %></i>
        </section>
      </div>
    </div>

    <div class="center">
      <div class="row">
        <% @lodge.images.each do |image| %>
          <%= image_tag image, class:'col'%>
        <% end %>
      </div>
    </div>
    
    <div class="under">
      <div class="container">
        <h4 class="child1-title center mt-5 mb-3" style="font-size: 35px;">宿について</h4>
        <div class="center">
          <%= @lodge.description %>
        </div>
      </div>
      <div class="container">
        <h4 class="contact child1-title center mt-5 mb-3" style="font-size: 35px;">お問い合わせ</h4>
        <i class="fas fa-phone center"><%= @lodge.phone%></i>
      </div>

      <div class="container mt-5 map-area">
        <h4 class="child1-title center mt-5 mb-2" style="font-size: 25px;">
          <i class="fas fa-map-marker-alt">地図</i>
          <h6 class="center">個人情報の場合もある為、おおよそのエリアを表示しています。</h6>
        </h4>
        <div class="row">
          <div id="map" class="col"></div>
        </div>
      </div>
    </div>

    <% if host_user_signed_in? && current_host_user.id == @lodge.host_user_id %>
      <%= link_to '宿の編集', edit_lodging_path(@lodge.id), method: :get, class:"edit-btn" %>
      <%= link_to '削除', lodging_path(@lodge.id), method: :delete, class:"lodge-delete" %>
    <% end %>
  </main>


  <footer>©️ Kanako Kurasawa2020</footer>

  <script type="text/javascript">
  function googleMap() {
    'use strict';
    var map = document.getElementById('map');
    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({ address: '<%= @lodge.prefecture_city%>', region: 'jp'}, function(results, status){

      if (status === 'OK' && results[0]) {
        new google.maps.Map(map, {
          center: results[0].geometry.location,
          zoom: 12
        });
      } else {
        alert('失敗しました。 理由:' + status);
        return;
      }
    });
  }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_KEY']%>&callback=googleMap"></script>
</body>

app/views/shared/_error_msg.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>

<header>
  
  <nav class="navbar navbar-expand-sm-md navbar-light bg-light">
    <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon" ></span>
    </button>
    <h1 class="nav-title center">
      <i class="fas fa-motorcycle"></i>Rider house book
    </h1>
    <div id="menu" class="collapse navbar-collapse">
      <ul class="nav-bar-nav">


        <li class="nav-item center mb-2">
          <%= link_to root_path do %>
            <i class="fas fa-home"></i>
          <% end %>
        </li>

        <% if host_user_signed_in? %>
          <li class="nav-item center"><%= link_to current_host_user.nickname, class:'user-nickname' %></li>
          <li class="nav-item center"><%= link_to 'ログアウト', destroy_host_user_session_path, method: :delete, class: 'logout'%></li>
          <li class="nav-item center"><%= link_to '宿を登録する', new_lodging_path, class:'new-lodge' %></li>
        <% else %>
          <li class="nav-item center"><%= link_to 'ホストになる', new_host_user_registration_path, class:'sign-up' %></li>
          <li class="nav-item center"><%= link_to 'ホストログイン', new_host_user_session_path, class:'login'%></li>
        <% end %>

        <%= form_with(url: search_lodgings_path, local: true, method: :get, class: "search-form mt-4 center") do |f| %>
          <%= f.text_field :keyword, placeholder: "都道府県・市区町村から探す", class: "input-box" %>
          <%= f.submit "search", class: "search-button"%>
        <% end %>
      </ul>
    </div>
  </nav>
</header>